### ISSUE TITLE
Can i embed a live streaming?

### ISSUE THREAD

**Issue by JeyEm1986** [jwplayer/wordpress-plugin#10]
I can, with new wordpress plugin jwplayer 7 (premium), embed a live streaming or only a streaming self-hosted(on demand)?

**Comment by rmnl** [comment]
@JeyEm1986 It depends on the type of manifest/playlist you are using, but if you can add the live streaming manifest/playlist file as an external url in the JW Player dashboard and it works then you can also use it with the plugin. Please look at our [support site](https://support.jwplayer.com/) for more [info on streaming](https://support.jwplayer.com/customer/portal/topics/564477-streaming/articles).
