### ISSUE TITLE
Signed links doesnt work on Wordpress

### ISSUE THREAD

**Issue by pavelsh07** [jwplayer/wordpress-plugin#11]
Hello!

I've installed JW Player Plugin 0.10.1 beta

I put option Timeout for signed links = 10 minutes

In my account properties i turn ON - Secure Video URLs and Secure player Embeds

So i put shortcode form wordpress on my pages like  [jwplayer YJrMPk6h]
and i cheked the code it like:

`<div id='jwplayer_YJrMPk6h_5MRs59jS_div'></div>
		<script type='text/javascript'>
			if(typeof(jQuery)=="function"){(function($){$.fn.fitVids=function(){}})(jQuery)};
			jwplayer('jwplayer_YJrMPk6h_5MRs59jS_div').setup(
				{"playlist":"http://content.jwplatform.com/jw6/YJrMPk6h.xml?exp=1457876407&sig=37fe8a44ac0346d2b2cd0a43f8881782"}
			);
		</script>
	</div></div></div>`

But video doesnt work
If i turn OFF SECURE it starts to work

Please check it 

As i understand systme generate new exp=1457876407&sig=37fe8a44ac0346d2b2cd0a43f8881782 

BUT it doesnt work

PLEASE let me know how to solve this issue with signed links... It doesn't work

THANKS!

**Comment by rmnl** [comment]
@pavelsh07 The text might not be perfectly clear, but you should only switch on secure video urls, not secure player embeds. The last is currently not working with the Wordpress plugin.

**Comment by rmnl** [comment]
@pavelsh07 Please try the code in [the 1.5.1 branch](https://github.com/jwplayer/wordpress-plugin/tree/1.5.1). Let me know if that works for you.

**Comment by pavelsh07** [comment]
OK! THANKS!

IT work's now!!!

Good


thank you!

2016-03-13 23:47 GMT+03:00 rmnl <notifications@github.com>:

> @pavelsh07 <https://github.com/pavelsh07> Please try the code in the
> 1.5.1 branch <https://github.com/jwplayer/wordpress-plugin/tree/1.5.1>.
> Let me know if that works for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jwplayer/wordpress-plugin/issues/11#issuecomment-196050280>
> .
>



-- 
С уважением, Руководитель Профбух8.ру
Павел Шерст
Написать отзыв <http://www.profbuh8.ru/feedback/>

+7 495 988 92 58
www.Profbuh8.ru <http://www.profbuh8.ru/>

<http://www.profbuh8.ru/>

**Comment by rmnl** [comment]
@pavelsh07 Thanks for providing feedback. Will close this issue now.
