### ISSUE TITLE
Plugin causes admin screens to go blank

### ISSUE THREAD

**Issue by seanlehane** [jwplayer/wordpress-plugin#13]
Hi, 

I've found this issue mentioned several times by others. When I have the plugin active, my Posts, Pages, Events, etc. admin screen in WordPress return no results. I can't edit anything. See the below screenshots: 

![screen shot 2016-03-18 at 12 22 21 pm](https://cloud.githubusercontent.com/assets/15848798/13885347/461cd52c-ed08-11e5-9fca-3963fbbbbba1.png)

After I turn off just this plugin, everything returns to normal: 

![screen shot 2016-03-18 at 12 22 57 pm](https://cloud.githubusercontent.com/assets/15848798/13885355/5417759c-ed08-11e5-8bf9-a3db9d00a36c.png)

**Comment by rmnl** [comment]
@seanlehane This is not the first time someone has mentioned this issue. It was also the [first issue ever reported for this repository](https://github.com/jwplayer/wordpress-plugin/issues/1).

The problem however is that we are and have not been able to reproduce this error on our own test and development servers, which makes it very hard to debug. It seems to be triggered only in some cases. Would you be willing to provide more info on your WP setup?

- Wordpress and PHP versions
- Previous version of JW Player plugin installed.
    - settings in this plugin (specially regarding shortcodes)
    - an example embed code you were using.
- Other plugins installed.
- info about the theme you are using.

**Comment by rmnl** [comment]
Closing due to lack of feedback...
