### ISSUE TITLE
Some videos are having an "error parsing shortcode"

### ISSUE THREAD

**Issue by seanlehane** [jwplayer/wordpress-plugin#15]
Hi, 

Today I activated your plugin on my WordPress website: http://www.ideacity.ca

For years, we'd been using the JW Player 6 WordPress plugin without issue. 

After turning off the JW6 and turning on your plugin, I followed the steps to import players and content, etc., and in most cases the videos are playing perfectly fine with our new Platform player we made. An example of a video that is working properly is this: http://www.ideacity.ca/video/james-hughes-transhumanism-2/

An example of one that is NOT working is this: http://www.ideacity.ca/video/art-mcdonald-explains-neutrinos/

When I look at the view-source of both posts, I see that one is rendering the player, and the other isn't. Screen shots below: 

WORKING:
![screen shot 2016-03-31 at 2 25 00 pm](https://cloud.githubusercontent.com/assets/15848798/14186589/1e6baf2c-f74d-11e5-82a0-a90e120067b3.png)

NOT WORKING:
![screen shot 2016-03-31 at 2 25 10 pm](https://cloud.githubusercontent.com/assets/15848798/14186578/0df703e4-f74d-11e5-9f5b-d196449c5e7a.png)

The short codes haven't changed. 

So I don't really know what to do. Any suggestions?

**Comment by rmnl** [comment]
Can you give the shortcodes that go with each of these?

**Comment by seanlehane** [comment]
Sure!

For the video that isn't work, this is the short code: [jwplayer mediaid="47659"] "Art McDonald"
For the video that IS working, this is the short code: [jwplayer mediaid="43989"] "James Hughes"

**Comment by rmnl** [comment]
@seanlehane I don't see any immediate issues with this shortcode. Can you check that the media that isn't working shows up properly in your JW Player account? It should be in there somewhere with the same title.

**Comment by seanlehane** [comment]
I don't know if this is potentially related, but when i look in my dashboard at JW Player, I see that there are probably 20 or so videos that seemed to get to the platform without any title reference. There were lots that came in as NoName, but that made sense because we often didn't title the videos properly when adding them via the JW6 plugin over the years. But for the ones that are blank, my only option is to select the embed link for the video, but via that it won't let me assign a title to the video.

**Comment by seanlehane** [comment]
![screen shot 2016-03-31 at 3 16 57 pm](https://cloud.githubusercontent.com/assets/15848798/14188028/e6d21b6c-f753-11e5-9cd5-d05814d8c5fb.png)

**Comment by rmnl** [comment]
@seanlehane This is very hard to debug, because I cannot see the exact metadata and URLs for this. Could you make a screenshot of the media details page for both the the working and non-working media in your Wordpress media library?

If you feel uncomfortable posting this on Github, please email: support@jwplayer.com
