### ISSUE TITLE
Error video after update player from 6 to 7 

### ISSUE THREAD

**Issue by franciscojosecv** [jwplayer/wordpress-plugin#18]
We just update the player version from 6 to 7, since then the videos is not working propertly, First  some videos does not load and in others case you just can see the half of the video and the other half in black screen. 

You can look in this link: [http://blog.hola.com/marta-gonzalez/2016/02/18/los-pirineos-a-caballo/](url)
Could you please give us a solution of this case? 
Best

**Comment by rmnl** [comment]
@franciscojosecv I see the problem with the video playing on a half black screen. This seems like a CSS styling conflict. JW Player 7 uses CSS and html to generate the player controls and video tag. Below is a response from one of our support engineers.

> One thing to also keep in mind when dealing with WP is that a lot of WP themes, even the default themes, mess up the player's CSS. 

> With JW7 this is even more prevalent, because regardless of rendering mode, the player controls will always be HTML. So if you run into this issue, you should look in your theme's CSS file for the word "video", as many themes are setting the rules on video tags. E.g.:

> max-width: 100%;

> Some themes are setting this more than once. In the Twenty Fourteen theme, this is set twice, causing the player to display with a black box around it.
