### ISSUE TITLE
Error activating Jw player

### ISSUE THREAD

**Issue by dgeekguy** [jwplayer/wordpress-plugin#19]
I could not activate JW player after installation. I am getting this error message

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '[' in /hermes/bosnaweb17a/b1151/ipg.lovefoundationngorg/lovefoundation/newwp/wp-content/plugins/jw-player/include/media.php on line 81 

The cause of this I could not know. Any ways of correcting this

**Comment by andy22andy** [comment]
I have the same problem.
Parse error: syntax error, unexpected
wp-content\plugins\jw-player\include\media.php on line 81

**Comment by rmnl** [comment]
@dgeekguy, @andy22andy Please provide more info on your Wordpress Setup. I am not able to reproduce this error. I just tried with a new clean install of Wordpress 4.5 and cannot reproduce this error.

- WP version
- PHP version
- Plugin version
- Did you have any previous version of our Plugin of someone else's JW Player plugin installed?

As far as I can see, this could be happening if you were using a previous version of our plugin and one of your media files has an invalid mime type in your database, although I was also not able to reproduce this. Just to be sure, please try replacing line 81 and change it from:

```php
	$sourceformat = ( $mime_type ) ? preg_split( '/\//', $mime_type )[1] : 'mp4';
```

to:

```php
	$mime_type_parts = ( $mime_type ) ? preg_split( '/\//', $mime_type ): false;
	$sourceformat = ( count( $mime_type_parts ) > 1 ) ? $mime_type_parts[1] : 'mp4';
```

Please let me know if that helps.

**Comment by dgeekguy** [comment]
•WP version=- 4.5
•PHP version ---5.3
•Plugin version -- 1.5.1
•Did you have any previous version of our Plugin of someone else's JW
Player plugin installed? ==no.


I cannot precisely find the code you sent after going to media.php line 81

Sincerely

Bermard

**Comment by rmnl** [comment]
It should be in [jw-player/include/media.php](https://github.com/jwplayer/wordpress-plugin/blob/develop/jw-player/include/media.php#L81). If not that would be very strange...

**Comment by dgeekguy** [comment]
I found it and replace it.  Activation was now successful. BUT I am having
problem with Plugin Authorization. I created an account with jw player. API
Key and API Secret I have from the account is not working. here is the
message gotting.." *Communications with the JW Player API failed. Please
try again later.* "

is it ok?, if Yes.  how soon will I try again

Thanks,

Bernard

**Comment by rmnl** [comment]
@dgeekguy Thank you for trying. Please make sure you've copied the key and secret correctly from your account. Also make sure you're not behind a proxy. There are no issues with the API server.

**Comment by dgeekguy** [comment]
I have tried it. I just register another account trying to get the API
code, the same error. Or is it as a result of the 81 error I change
earlier. I m just guessing.

I keep getting *Communications with the JW Player API failed. Please try
again later.*



*Bernard*

**Comment by rmnl** [comment]
@dgeekguy I've just tried registering a new account and activating the plugin and all works fine. Also when you give the wrong credentials it will let you know, so it seems something in your PHP or Wordpress setup prevents it from talking to our API.

What I can suggest is changing the API Url to https to see if that unblocks the issue. So [in line 15 of the jw-player/include/jwplayer-api.class.php file](https://github.com/jwplayer/wordpress-plugin/blob/develop/jw-player/include/jwplayer-api.class.php#L15) change:

```php
	private $_url = 'http://api.jwplatform.com/v1';
```
to
```php
	private $_url = 'https://api.jwplatform.com/v1';
```

If this does not help, I suggest you contact support@jwplayer.com about this issue, because they might be able to help you debug this issue (and it is safer to pass credentials for debugging like email and api key this way).

**Comment by rmnl** [comment]
Closing this issue after two weeks of inactivity.
