### ISSUE TITLE
Please add closed caption file support

### ISSUE THREAD

**Issue by mwarner** [jwplayer/wordpress-plugin#2]
This feature appears to be missing.  I can add subtitles to the video, and the caption file appears in the track tag, but no captions appear.  There is no button to enable or disable captions in the player.

**Comment by rmnl** [comment]
There is captioning support in the JW Player dashboard. If you add tracks to your videos in JW Player they should also display with the tracks in the player. If this does not work for you, please contact [our support](https://support.jwplayer.com/).
