### ISSUE TITLE
WP-Rocket compatiblity

### ISSUE THREAD

**Issue by donnikhan** [jwplayer/wordpress-plugin#21]
SINGLE LINE EMBED CODE in the TEXT MODE of the POST EDITOR gets moved to the head when WP-ROCKET is enabled on the page

**Comment by rmnl** [comment]
@donnikhan Please explain how you are using the plugin?

**Comment by InsiderPerks** [comment]
We have this same issue with the standard settings on WP Rocket but we are not using the plugin. We are simply using the embed code for the cloud hosted content. Although WP Rocket is being used to combine/minify javascript, it is not doing so to the JW Player javascript. Instead, when WP Rocket is active, it is relocating the JW Player javascript to the header. There are no settings in the plugin that would specifically do this, as it does not affect other similar javascript. I can tell the plugin to not cache the specific page the video is on and that solves but the problem, but it's not ideal.
