### ISSUE TITLE
Communications with the JW Player API failed

### ISSUE THREAD

**Issue by jmgrand** [jwplayer/wordpress-plugin#23]
Hello,

I have a bug trying to authorize the plugin after entering my API key and API secret... Each time I try, I get this message : "Communications with the JW Player API failed. Please try again later."

if somebody have an idea...
thanks a lot

Jean-Michel

**Comment by rmnl** [comment]
@jmgrand This usually happens because your server and/or network is configured to block calls to external domains. This means the plugin cannot reach the API server. Please verify that you can call external domains from your server in php.

**Comment by jmgrand** [comment]
@rmnl thanks for your answer... do you have a method to know that on my server ?

**Comment by rmnl** [comment]
@jmgrand You might give [this](http://stackoverflow.com/questions/2280394/how-can-i-check-if-a-url-exists-via-php#answer-2280413) a try?

**Comment by rmnl** [comment]
@jmgrand Did it work?
