### ISSUE TITLE
Video uploads occurring over http from within https WP admin

### ISSUE THREAD

**Issue by anthony-j-castro** [jwplayer/wordpress-plugin#24]
Our writers are trying to upload a video from within Media Gallery > JW Player > Add New. The upload is silently failing, with an error being thrown in the log:

`Mixed Content: The page at 'https://xxxx.wordpress.com/wp-admin/post.php?post=xxxx&action=edit' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://upload.jwplatform.com/v1/videos/upload/resumable?api_format=json&key=xxxxxxxx'. This request has been blocked; the content must be served over HTTPS.`

**Comment by rmnl** [comment]
@anthony-j-castro Try out version 1.5.3. This should fix your issue. Thanks for reporting.

**Comment by anthony-j-castro** [comment]
Thanks @rmnl! We're a Wordpress VIP customer, any idea of when 1.5.3 might be submitted to update the shared version of the plugin?

**Comment by rmnl** [comment]
@anthony-j-castro I will have to discuss this internally, because the review process is currently a bit tedious.

**Comment by anthony-j-castro** [comment]
@rmnl Gotcha. Thanks for the quick turnaround!
