### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Steamd3mon** [jwplayer/wordpress-plugin#27]
Will not activate, it keeps throwing this error:

Parse error: syntax error, unexpected T_FUNCTION in /wp-content/plugins/jw-player/include/ajax.php on line 5

**Comment by rmnl** [comment]
@Steamd3mon See [this Stackoverflow](http://stackoverflow.com/questions/3657357/unexpected-t-function-error-when-using-function-array-matches) question.

It seems that you're server is running a very old version of PHP. Support for version 5.2 ended January 6, 2011.
