### ISSUE TITLE
Cannot upload files with accented characters in file name

### ISSUE THREAD

**Issue by waxidiotic** [jwplayer/wordpress-plugin#28]
EXPECTED BEHAVIOR
As a publisher, I would like to be able to upload files via the Wordpress plugin whose file names contain accented characters. I am able to upload the same files successfully via the JW Player Dashboard.

ACTUAL BEHAVIOR
When trying to upload a file whose name contains an accented character via the plugin, the upload dialog stalls on _Uploading..._ with no progress being shown.

![screen shot 2016-07-01 at 11 12 47 am](https://cloud.githubusercontent.com/assets/8037469/16525939/d3ee9e64-3f7c-11e6-8724-09bf7986f47d.png)

And the following error gets thrown in the console:
`upload.js?ver=4.5.3:540 Uncaught SyntaxError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'attachment; filename="Alexs Test Olé.mp4"' is not a valid HTTP header field value.`

To reproduce this issue, I used a file that I renamed to "Alex's Test Olé.mp4"

(Re: Case #85236 - this is a note for me)

**Comment by rmnl** [comment]
@waxidiotic I've verified and fixed the problem. [Version 1.5.4](https://github.com/jwplayer/wordpress-plugin/tree/1.5.4/jw-player) of the plugin should make this work.

**Comment by waxidiotic** [comment]
It works. Thanks @rmnl!

**Comment by rmnl** [comment]
Thanks for verifying @waxidiotic!
