### ISSUE TITLE
installed beta jwplayer and it hides all my footer widgits on wordpress

### ISSUE THREAD

**Issue by tastetwist** [jwplayer/wordpress-plugin#3]
installed beta jwplayer and it hides all my footer widgits on wordpress

**Comment by rmnl** [comment]
@tastetwist Please provide additional info about your setup, which widgets you use, etc. Without the right information it is impossible for us to reproduce this issue you are experiencing.

**Comment by tastetwist** [comment]
just embed code .. text info

**Comment by tastetwist** [comment]
SO I am trying to embed a video banner using the JW player embed code only - with no controls - auto loop - and responsive .. is this possible with this plugin ?

**Comment by rmnl** [comment]
@tastetwist This plugin is meant to publish video's in your post or in Wordpress pages. It's not for editing the theme of your install. In this case simply setup a player and video in your [JW Player account](https://dashboard.jwplayer.com/) and use the publish wizard to generate a regular embed code for your footer HTML. If you have any problem with this, please [refer to our support site](https://support.jwplayer.com), which has documentation on how to use and embed our player.
