### ISSUE TITLE
Getting  Authorization issue(Communications with JWplayer API failed)

### ISSUE THREAD

**Issue by Velahellou** [jwplayer/wordpress-plugin#34]
As you suggest by Jw player support team upgraded all the versions of php and wordpress still we are getting the authoarization error in the wordpress admin page, Our previous version of php was 5.5 now upgraded to php7, We feel that this would be an configuration issue rather than version issue. Please help here to slove the issues.
![jwplayer](https://cloud.githubusercontent.com/assets/20776404/17300051/aabfad36-5808-11e6-8a0d-cd45338c9bc2.jpg)

**Comment by rmnl** [comment]
@Velahellou Can you change the function `jwplayer_login_verify_api_key_secret` in `jw-player/include/login.php` on [line 118](https://github.com/jwplayer/wordpress-plugin/blob/develop/jw-player/include/login.php#L118) from:

```php
function jwplayer_login_verify_api_key_secret( $key, $secret ) {
	// Create an API object with the provided key and secret.
	$api = new JWPlayer_api( $key, $secret );
	$response = $api->call( '/accounts/show' );
	return jwplayer_api_response_ok( $response );
}
```
to:
```php
function jwplayer_login_verify_api_key_secret( $key, $secret ) {
	// Create an API object with the provided key and secret.
	$api = new JWPlayer_api( $key, $secret );
	$response = $api->call( '/accounts/show' );
	print_r($response);
	exit(1);
	return jwplayer_api_response_ok( $response );
}
```

After changing, please try to authenticate again and please report which error you are getting.

**Comment by Velahellou** [comment]
Hi ,

After making this changes I’m getting an error “Error: call to JW Player API failed “  in the admin page attached the image for your reference.

[cid:image001.png@01D1EC9F.9DAE8330]


Thanks,
Vela

**Comment by rmnl** [comment]
@Velahellou Ok, let's try another change. Hopefully we'll get a little closer to the problem now.

Please change the `public function call` in `jw-player/include/jwplayer-api.class.php` on line 83 and let me know again.

#### From:
```php
	public function call( $call, $args = array() ) {
		$url = $this->call_url( $call, $args );

		$response = null;
		switch ( $this->_library ) {
			case 'wpvip':
				$response = vip_safe_wp_remote_get( $url );
				break;
			case 'wp':
			default:
				$response = wp_remote_get( $url );
			break;
		}

		if ( is_wp_error( $response ) ) {
			return 'Error: call to JW Player API failed';
		}

		$response = wp_remote_retrieve_body( $response );
		$decoded_response = json_decode( $response, $assoc = true );
		return $decoded_response;
	}
```
#### To:
```php
	public function call( $call, $args = array() ) {
		$url = $this->call_url( $call, $args );

		$response = null;
		switch ( $this->_library ) {
			case 'wpvip':
				$response = vip_safe_wp_remote_get( $url );
				break;
			case 'wp':
			default:
				$response = wp_remote_get( $url );
			break;
		}

		if ( is_wp_error( $response ) ) {
			print_r($response);
			exit();
			return 'Error: call to JW Player API failed';
		}

		$response = wp_remote_retrieve_body( $response );
		$decoded_response = json_decode( $response, $assoc = true );
		return $decoded_response;
	}
```

**Comment by Velahellou** [comment]
After making this change I am getting an blank page. Please refer  the screenshot.

Screenshot:-

[cid:image001.png@01D1ECAE.E7878CE0]

**Comment by rmnl** [comment]
@Velahellou Try again. This time change it to:

```php
	public function call( $call, $args = array() ) {
		$url = $this->call_url( $call, $args );

		$response = null;
		switch ( $this->_library ) {
			case 'wpvip':
				$response = vip_safe_wp_remote_get( $url );
				break;
			case 'wp':
			default:
				$response = wp_remote_get( $url );
			break;
		}

		if ( is_wp_error( $response ) ) {
			print_r($response->errors);
			exit();
			return 'Error: call to JW Player API failed';
		}

		$response = wp_remote_retrieve_body( $response );
		$decoded_response = json_decode( $response, $assoc = true );
		return $decoded_response;
	}
```

**Comment by Velahellou** [comment]
Same blank screen. In this server we have updated to php7 will this have any issues?.

Thanks,
vela

**Comment by rmnl** [comment]
@Velahellou OK, let's try this.

Can you create a php file on your server with the content below and open the file in your browser. I'm curious to what the response is.

```php
<?php
// create a new cURL resource
$ch = curl_init();

// set URL and other appropriate options
curl_setopt($ch, CURLOPT_URL, "https://api.jwplatform.com/");
curl_setopt($ch, CURLOPT_HEADER, 0);

// grab URL and pass it to the browser
curl_exec($ch);

// close cURL resource, and free up system resources
curl_close($ch);
```

**Comment by Velahellou** [comment]
Hi ,

Enclosed the test page and its response is ok I tried this yesterday itself is responded me back with ok.

status: ok resource: api-server timestamp: 1470134483

http://prestage.hellou.co.uk/jw_test.php

**Comment by rmnl** [comment]
@Velahellou OK, this means you can access the server. Please add the following two lines to the file you created:

```php
echo "<hr>";
echo time();
```

Is the timestamp you get back from the server similar to the one below? It could be that the time codes are off, but this should have given you another error to begin with.

**Comment by Velahellou** [comment]
Ok In the mean time I just debugged the file jwplayer-api.class.php, I am getting this URL in the call function is this one we required?.   When I called this url I am getting this error.
status: error
code: ParameterMissing
title: Missing Parameter
message: api_format: Missing value


http://api.jwplatform.com/v1/accounts/show?

Thanks,
vela

**Comment by Velahellou** [comment]
Its just giving the excat time no errors.

status: ok resource: api-server timestamp: 1470135012
________________________________
1470135012

Thanks,
vela

**Comment by rmnl** [comment]
@Velahellou Yes, the `api_format` parameter is compulsory, but you also need to sign the call. This should all be done automatically.

**Comment by rmnl** [comment]
@Velahellou Are you using another JW Player plugin (official or third party) ?

**Comment by Velahellou** [comment]
Just tried that plugin since its working I tried that plugin Now I have disabled the plugin and tried still same error.



Thanks,

Vela

**Comment by Velahellou** [comment]
Ok..Just shared the info is that helps to sort out the issue.

**Comment by Velahellou** [comment]
I justed added some print funtions to understand the flow and got these messages getting parameter error. Hope this helps .

Inside the function callhttp://api.jwplatform.com/v1/accounts/show?Inside the case defaultpArray ( [headers] => Array ( [cache-control] => no-cache [content-type] => text/plain; charset=utf-8 [date] => Tue, 02 Aug 2016 11:31:10 GMT [pragma] => no-cache [server] => openresty [content-length] => 98 [connection] => Close ) [body] => status: error code: ParameterMissing title: Missing Parameter message: api_format: Missing value [response] => Array ( [code] => 400 [message] => Bad Request ) [cookies] => Array ( ) [filename] => )

Thanks
vela

**Comment by rmnl** [comment]
@Velahellou The url you're using is unsigned and misses all parameters. I don't know why that is happening, but at this point I'm assuming this is because of something in your setup. 

- What are your versions of WP and the JW-player plugin?
- Disable your plugins one by one and try again.

Apart from the version of PHP, this can also be happening because of the plugins you've installed (they might alter requests), the theme you're using the version of WP, the version of the plugin, firewall settings on your host, etc.

**Comment by Velahellou** [comment]
I will try to do this, This is the wordpress version I’m using Wordpress 4.5.3  and Jw Player 1.5.5, Theme which we use is the customized one for our own.

Thanks,
Vela

**Comment by Velahellou** [comment]
Hi ,

I have removed all the plugins and changed the theme to default one and tried to connect to JWPlayer through its plugin, Still getting the same error.

I feel some configuration or parameter is missing not sure why its not accepting with the default wordpress.
[cid:image001.png@01D1ECC1.D3295680]

Thanks,
Vela

From: Velappan Velappan - helloU
Sent: Tuesday, August 2, 2016 1:15 PM
To: 'jwplayer/wordpress-plugin'; jwplayer/wordpress-plugin
Cc: Mention
Subject: RE: [jwplayer/wordpress-plugin] Getting Authorization issue(Communications with JWplayer API failed) (#34)

I will try to do this, This is the wordpress version I’m using Wordpress 4.5.3  and Jw Player 1.5.5, Theme which we use is the customized one for our own.

Thanks,
Vela

**Comment by rmnl** [comment]
@Velahellou I'm sorry but I don't think I will be able to help you on this page with this issue without accessing your server. Maybe you can [contact our support team](https://support.jwplayer.com/customer/portal/emails/new) (you have to be logged in to your JW Player account) and coordinate with them if you want us to take a deeper look at it. As far as I can see all the info for your account seems to be perfectly fine. Please make sure you refer to our conversation on [this page](https://github.com/jwplayer/wordpress-plugin/issues/34).

**Comment by rmnl** [comment]
**Please note** that I have edited some of the comments to remove the _email reply part_ that was included with those comments.

**Comment by Velahellou** [comment]
Thanks, I’m getting this error now.

Inside the function callhttp://api.jwplatform.com/v1/accounts/show?Inside the case defaultpWP_Error Object ( [errors] => Array ( [http_request_failed] => Array ( [0] => name lookup timed out ) ) [error_data] => Array ( ) ) Array ( [http_request_failed] => Array ( [0] => name lookup timed out ) )

Thanks,
Vela

**Comment by rmnl** [comment]
@Velahellou OK, this would indicate you're server is unable to find the DNS entries for the API domain. Still a bit strange, because it seems the [curl test script you made](http://prestage.hellou.co.uk/jw_test.php) can find it.

**Comment by Velahellou** [comment]
Yes really strange, Small issue it would be not able to figure it out ☹

Thanks,
Vela

**Comment by Velahellou** [comment]
What is wpvip & wp in the jwplayer plugin code, What It denotes ?.

Thanks.
Vela

**Comment by rmnl** [comment]
This plugin works for regular Wordpress installs and Wordpress installs on [their VIP platform](https://vip.wordpress.com/), which has a couple of code differences regarding communication, security and storage. Wordpress requires the usage of some functions on the VIP Platform, but those functions are not available in regular Wordpress installs. The plugin uses different functions based on which platform is used.

**Comment by Velahellou** [comment]
Thanks for update.

Thanks,
vela

**Comment by Velahellou** [comment]
I think the issue from the DNS hellou.co.uk we were not able to map all our servers are connected with Rackspace do we need to enable any settings in server level?.

Thanks,
vela

**Comment by rmnl** [comment]
I'm guessing something should be changed in your server setup, but this is probably something your sysadmin should look at. Also Rackspace mentions their _"fanatical"_ support, so they can probably help out too.

**Comment by Velahellou** [comment]
Hi ,

We are currently using rackspace server for our environment when we tried to connect the jwplayer through wordpress plugins we are getting this error, Do we enable any specific ip of yours. Please let us know.

Thanks,
vela

**Comment by rmnl** [comment]
@Velahellou  This is an environment issue and I cannot help you with those. You'll have to discuss this with whoever manages your servers.

**Comment by Velahellou** [comment]
Hi ,

I have connected with them and we were able to curl the ip, how the response will be available from your end, Its getting bit tricky. Currently we have plain wordpress only with jwplayer plugin which also throwing the same error as 400 Bad request, I feel there should some parameter request is missing if you could share more info the required details to connect will be helpful for me for the debugging.

Thanks,
vela

**Comment by Velahellou** [comment]
This is the out of the call Array args values is empty here.

Login page9XNL1ZfdEaDpCZt2KugT8wuu9DKlh6il
argsArray ( ) URL_____________________________________https://api.jwplatform.com/v1/accounts/show?
Call responseArray ( [headers] => Array ( [cache-control] => no-cache [content-type] => text/plain; charset=utf-8 [date] => Wed, 03 Aug 2016 14:48:56 GMT [pragma] => no-cache [server] => openresty [content-length] => 98 [connection] => Close ) [body] => status: error code: ParameterMissing title: Missing Parameter message: api_format: Missing value [response] => Array ( [code] => 400 [message] => Bad Request ) [cookies] => Array ( ) [filename] => ) Response

Thanks,
vela

**Comment by Velahellou** [comment]
Hi ,

https://api.jwplatform.com/v1/accounts/show? After this how you are appending the values, When I tried with other server values getting appened here. Also I have got an error message from server that

PHP Warning:  http_build_query() expects at most 3 parameters, 4 given in /var/www/wordpress/wp-content/plugins/jw-player/include/jwplayer-api.class.php on line 78, referer: http://162.13.152.60/wordpress/wp-admin/admin.php?page=jwplayer_login_page

Will it required any other plugin or any clues?.

Thanks,
Vela

**Comment by Velahellou** [comment]
I am talking to them to, If you could provide few more details on the datetime usage and how you build the parameters so that I can sort this issue asap.

Thanks,
vela

**Comment by Velahellou** [comment]
Hi ,

http_build_query is not building the required parameters. Do you faced any issues.

Thanks,
vela

**Comment by rmnl** [comment]
@Velahellou Please look at the [API Docs](https://developer.jwplayer.com/jw-platform/reference/v1/) for all info or to the [authentication page](https://developer.jwplayer.com/jw-platform/reference/v1/authentication.html) for specific info about request signing.

**Comment by Velahellou** [comment]
We have sorted the issues, PHP alone not needs to upgraded we need to update the apache2.4m http_build_query wont work in php5.3.

Thanks,
vela

**Comment by rmnl** [comment]
Good news!

**Comment by mayank199** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/33648915/56361127-3760e900-6204-11e9-8208-9c6243c3b0ce.png)


Getting this error when i tried to upload file from my asp.net project.
