### ISSUE TITLE
Could not find source file: Error message

### ISSUE THREAD

**Issue by j3dj3d** [jwplayer/wordpress-plugin#35]
I have a problem when I add a self-hosted video to a page in my Wordpress. The error message is printed in the produced page that the end user would see. I've done a video showing my problem:
https://youtu.be/jCOc-aukyqs

Thanks for any advice.

**Comment by rmnl** [comment]
@j3dj3d Please make sure that there are no interfering plugins installed and activated. It seems there are still other plugins. The JW Player settings I see in the video, does not exist. Also the current plugin does not require a player key. 

The settings for the plugin can be found under the settings menu (see screenshot).

![settings menu](http://s16.postimg.org/f6kgqbqzp/Screen_Shot_2016_09_21_at_13_44_10.png)

It is possible that the other plugin also uses the `jwplayer` shortcode.

**Comment by j3dj3d** [comment]
Thanks. It's now working fine. I deactivated this conflicting plugin:
Simple shortcode for JW Player 7
Activate | Edit | Delete
Plugin for JW player 7 that is compatible with the basic shortcodes from JW player 6 plugin

Version 1.2.1 | By Simon Dirlik | View details

**Comment by rmnl** [comment]
Ok, thanks for letting me know it's working now. I'll close this issue.
