### ISSUE TITLE
JW Upload Not Working Over HTTPS on Wordpress VIP

### ISSUE THREAD

**Issue by escobar022** [jwplayer/wordpress-plugin#41]
On Wordpress Admin area when uploading an mp3 via the media uploader using JW Plugin we are receiving an error which causes the upload to fail if the admin is served over https.
The mixed content error is with the page requesting http://upload.jwplatform.com/v1/videos/upload/resumable?api_format=json&key=XXXXX
It seems that this is breaking the upload to the JW service via the plugin.
The url is requested by this file below in the plugin on line 591. 
jw-player-1.5.1/static/js/upload.js 
It seems that the service sets this url request so we are unable to change this.

**Comment by rmnl** [comment]
@escobar022 Can you try upgrading the plugin to the latest version? The admin https issue should be fixed in [version 1.5.3](https://github.com/jwplayer/wordpress-plugin/releases/tag/1.5.3). From the looks of your comment, you're still on v1.5.1.

**Comment by escobar022** [comment]
Hello,
It looks like the v1.5.3 is not available on Wordpress VIP. Could you suggest a workaround?
Andre

**Comment by rmnl** [comment]
If you can edit the code of the plugin on VIP, it should be easy, but if you can't then I don't see an easy workaround and I'll ask to see if we can push a new version to VIP (this is a bit of a tedious process, which means we usually skip minor versions).

**Comment by HeidiW** [comment]
@rmnl Today we received this email via support from Wordpress VIP:

> Thank you for the confirmation. If you can submit the 1.5.3 version through the regular plugin update submission process, we'll make sure to review the changes and update the plugin on our side shortly.
> 
> Let us know when the update has been submitted.
> 
> Kindly,
> Stefan Carstocea | WordPress.com VIP
> http://vip.wordpress.com/documentation/

**Comment by rmnl** [comment]
Should be fixed with v1.6.0
