### ISSUE TITLE
Communications with the JW Player API failed. Please try again later.

### ISSUE THREAD

**Issue by verovitaly** [jwplayer/wordpress-plugin#42]
Not possible to Authorise it.

Errors:
Warning: http_build_query() expects at most 3 parameters, 4 given in /mydomainname.com/html/wp-content/plugins/jw-player/include/jwplayer-api.class.php on line 42

Warning: http_build_query() expects at most 3 parameters, 4 given in /mydomainname.com/html/wp-content/plugins/jw-player/include/jwplayer-api.class.php on line 78

How to resolve it?

**Comment by rmnl** [comment]
@verovitaly Can you tell me how I can reproduce this error?

**Comment by verovitaly** [comment]
Ok. You need website (Wordpress) :-) 
1) Install plugin JWPlayer for Wordpress (author JW Player)
2) Activate it.
3) Go to Settings-JW Player
4) Click on link Authorisation or Authorize.
5) Type or Paste API key&API security code and click button.

After this 5 steps you see that errors:
Communications with the JW Player API failed. Please try again later.
Warning: http_build_query() expects at most 3 parameters, 4 given in /mydomainname.com/html/wp-content/plugins/jw-player/include/jwplayer-api.class.php on line 42

Warning: http_build_query() expects at most 3 parameters, 4 given in /mydomainname.com/html/wp-content/plugins/jw-player/include/jwplayer-api.class.php on line 78

**Comment by rmnl** [comment]
@verovitaly What version of PHP are you on? This is essential behavior of the plugin and it's unclear why it happens to you but not to me

**Comment by verovitaly** [comment]
I dont knew how to check but on hosting knowledge base found that current version php7

**Comment by rmnl** [comment]
@verovitaly Please run a check, because this seems to be an issue if you're using a version below PHP 5.4.0 ([see here](http://us3.php.net/manual/en/function.http-build-query.php)). To check your version create a file called info.php (or whatever you like) with:

```php
<?
phpinfo();
```

Next upload it to your server and call it in your browser.

**Comment by verovitaly** [comment]
Yes you are right, my version of php - PHP Version 5.3.29

Is it mean that I need update PHP before using JW Player Plugin?

**Comment by rmnl** [comment]
@verovitaly Unfortunately yes, because URL encoding will not happen properly without it.

**Comment by verovitaly** [comment]
And what version php I need?

**Comment by rmnl** [comment]
@verovitaly To be on the safe side (regarding security issues) I would suggest to get one of the latest releases of PHP. The latest version of php5 is 5.6.27.

**Comment by verovitaly** [comment]
ok thank.
