### ISSUE TITLE
Error loading JWplayer

### ISSUE THREAD

**Issue by Kneibe** [jwplayer/wordpress-plugin#47]
Hi there

I have a problem setting up my wordpress homepage with jwplayer. 
I would like to put a few m4a-audio file son my page.

I have a jwplayer account, I've updated the plugin to jwplayer 7 for Wordpress 1.3.3.

When loading the page I get the mesage "Error loading player: No playable sources found".
This is the page: [http://www.soulsurvivors.dk/audio/demo-medley/]

The weird thing is, that I've published these mp3 earlier without any problems: 
[http://www.soulsurvivors.dk/audio/live-metronomen-2015/](url)

It could be the Player library URL which is wrong. How do I find the right library name?

Please help :)

**Comment by rmnl** [comment]
@Kneibe You are not using [the official JW Player plugin](https://wordpress.org/plugins/jw-player/). Go [here](https://wordpress.org/support/plugin/jw-player-7-for-wp) for help with [JW Player 7 for Wordpress 1.3.3](https://wordpress.org/plugins/jw-player-7-for-wp/).

**Comment by Kneibe** [comment]
@rmnl 
allright I downloaded and installed the newest player - thanks!
But my jwplayer setup doesn't give me the oportunity of specifying the full url of jwplayer.js or pasting my license key. See enclosed screendump.
![image](https://cloud.githubusercontent.com/assets/23632263/20486435/fed060ba-afff-11e6-8f83-c9d09412fdad.png)
