### ISSUE TITLE
JW Player plugin issue in admin, with media upload

### ISSUE THREAD

**Issue by jigneshnakrani088** [jwplayer/wordpress-plugin#48]
We are facing an issue in admin panel due to JW Player plugin, 

1. when we are embedding JWplayer video(shortcode) in a post via ADD MEDIA 

2. and then we try uploading new Featured Image

 it throws JS error and the image does not upload screenshot attached.

Step:1 (Add Media)

![screen shot 2016-12-01 at 7 31 15 pm](https://cloud.githubusercontent.com/assets/9261540/20796751/a0a054f4-b7fd-11e6-8e75-3e9d02963221.png)

Step:2 (Featured Image)

![screen shot 2016-12-01 at 7 31 56 pm](https://cloud.githubusercontent.com/assets/9261540/20796780/be82fbd4-b7fd-11e6-9fdf-c6758aa1a272.png)

Step:3 (No upload, js error)

![screen shot 2016-12-01 at 7 32 25 pm](https://cloud.githubusercontent.com/assets/9261540/20796786/c9076f86-b7fd-11e6-8177-402925717ec1.png)

**Comment by rmnl** [comment]
@jigneshnakrani088 Can you explain how this is an issue with the plugin? Uploading images is not part of the plugin. Are you sure this is not caused by another thing?
