### ISSUE TITLE
Is It Possible to Add Authoring Page Widget to a Custom Post Editor?

### ISSUE THREAD

**Issue by VanessaKing** [jwplayer/wordpress-plugin#54]
In addition to the JW Player plugin, I'm using a plugin in a client project that creates articles/posts using custom posts. Is it possible to include or add the authoring page widget to a custom post editor? If so, is there a reason it's not appearing? Either way, how can I resolve it?

Thanks in advance!

**Comment by rmnl** [comment]
@VanessaKing It's probably possible to show the widget on custom posts page.

In the current code the widget code is activated with the `add_meta_box` function. This happens [here](https://github.com/jwplayer/wordpress-plugin/blob/develop/jw-player/include/media.php#L170). 

As you can see the widget is added for `$screen`s of type `post` and `page`. If you know the exact `$screen` name you can add an additional line to the code for the type you want.

You can find more info on the `add_meta_box` function [here](https://developer.wordpress.org/reference/functions/add_meta_box/).

**Comment by VanessaKing** [comment]
Thanks so much!
