### ISSUE TITLE
Shortcodes for JW Player 7 Wordpress plugin

### ISSUE THREAD

**Issue by IndiParker** [jwplayer/wordpress-plugin#56]
Hi,

I have sent a few messages to George at support:

George
JW Player
Support Engineer

Who suggested I contact you here for my issues.

I was made aware by George, I should upgrade to JW Player 7 - as I am currently using JW 6.

Upon installing it the news update and installing this new plugin, I notice none of my videos display. 

1. SHORTCODES
They use shortcodes like this in in posts:

Single Videos:
[jwplayer file="https://www.youtube.com/watch?v=YDUXzmvvfw0" image="https://img.youtube.com/vi/YDUXzmvvfw0/0.jpg" stretching="uniform" controlbar="bottom"]

For playlists:
[jwplayer playlistid="143039" listbar__position="bottom"]

Therefore, I need to know how to migrate all my posts to make the new player visible? What shortcodes should I use? 

I have lots of posts with video links in them. So, I do need a quick way to solve this. Otherwise, it will impact my very active site. One by one is a huge task.

Also, playlists, how do I recover those? As I have many posts with playlists which are no.1 in Google which are being viewed every day.

2. MIGRATION OF PLAYLISTS & PLAYERS
 I noticed the plugin says it will migrate players and playlists. I did the migration but all I had transferred over was the players, not my playlists in Wordpress.

How do I fix this?

Help with the above will be highly appreciated. The more info you can provide the better please.

Regards,
Indi

**Comment by rmnl** [comment]
The migration tool is geared towards the most common uses of our previous plugin. If you use highly customized shortcodes or plugins that interfere with Wordpress on a lower lever, the migration might fail. In that case you should migrate either manually or if you have a pattern you can use a tool to substitute your shortcodes. In all normal use cases the migration tool should take care of your migration.

**Please note** that we always advice to confirm the proper working of the migration in a non-production environment before running it in your production environment. If you do not have multiple environments, please make sure you have a snapshot of your site/database that you can restore if the migration fails.
