### ISSUE TITLE
Poster image for external videos 

### ISSUE THREAD

**Issue by mclblock** [jwplayer/wordpress-plugin#57]
Hi

I have added a video to a page from an external URL but it only shows me the default posterimage. Is there a way to change the poster image/thumbnail? Due to compliance reasons we can't have videos hosted on the JW Platform so I disabled the "Sync media to JW Player".

Steps
1. WP-Admin, Pages, edit page
2. Click Add Media
3. Go to JW Player
4. Click Add New
5. Click URL button
6. Paste this URL: https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
7. Click Add Media Reference
8. Click "Click to use this video"
9. Preview the page
10. Note that the default poster image is shown. There is no option for CMS editors to change the Poster image like they were able to in JW6 (see "Thumbnail" on  https://support.jwplayer.com/customer/portal/articles/1403714-jw6-wordpress-plugin-reference)

See attached screenshot

![capture](https://cloud.githubusercontent.com/assets/16672507/26490836/e21f1532-4204-11e7-8858-64e51170274d.PNG)

Thanks

**Comment by rmnl** [comment]
Our plugin is build around our video platform. If you do not wish to use our video platform we recommend you look at the [JW Player 7 for WordPress Plugin](https://wordpress.org/plugins/jw-player-7-for-wp/) that is made by another company.
