### ISSUE TITLE
Jw player shortcode and register the video as attached media in wordpress, issue

### ISSUE THREAD

**Issue by stiandk** [jwplayer/wordpress-plugin#58]
We have used the older version of jwplayer plugin for several years and now we´r upgrading to jwplayer 7 plugin version 1.6.0 

We made a theme where we added a function where it´s easy to insert wordpress media files using jwplayer.  it works but there´s one problem that we did not have with the old versions of the plugin, when adding a wordpress video to a post wordpress still se that video as unattached .  
We need this to work as we often delete unattached media on several of our sites.

Videos is inserted using shortcodes like this [jwplayer mediaid="3985"]

We modified our theme´s function.php file so it works with the plugin, it looks like this

`function incidentshare_enqueue_jwp_scripts()
{ 
// For either a plugin or a theme, you can then enqueue the script:
wp_enqueue_script( 'incidentshare_jwp_script', '/wp-content/uploads/jwplayer-7.10.4/jwplayer.js', array(), null, false);
wp_add_inline_script( 'incidentshare_jwp_script', 'jwplayer.key="xxx";');
}
add_action( 'wp_enqueue_scripts', 'incidentshare_enqueue_jwp_scripts' );
`

**Comment by rmnl** [comment]
Thank you for the suggestion.
