### ISSUE TITLE
Ad some options for a 9:16 aspectratio

### ISSUE THREAD

**Issue by swissky** [jwplayer/wordpress-plugin#69]
Hey, can you add a option to add some Code für a Portrait Video like 9:16? 
https://kevinkyburz.staging.wpengine.com/iphone-x-review-eine-neue-aera-von-smartphones/

**Comment by rmnl** [comment]
You should be able to set the player dimensions inside the dashboard. If the 9:16 aspect ratio is not available, you can do this with the API.

1. Create _clack-cli_
  ```bash
  pip install clack-cli==2.0.0b9
  ```

2. Get [your API credentials](https://dashboard.jwplayer.com/#/account/apicredentials).

3. List your players:
  ```bash
  clack call -a ms1 -k <API_KEY> -s /players/list
  ```
  You'll be asked to insert `<API_SECRET>`.

4. Find the `<PLAYER_KEY>` for the player that you wish to change.

5. Update the player:
  ```bash
  clack call -a ms1 -k <API_KEY> -s /players/update "{'player_key': '<PLAYER_KEY>', 'aspectratio': '9:16'}"
  ```
  You'll be asked for your `<API_SECRET>` again.

6. Done (You can repeat step 3 to confirm the changes).

**Comment by swissky** [comment]
Thank you. I will try it with wpEngine. I hope i get an server access.

**Comment by swissky** [comment]
@rmnl Is there another way? wpEngine give me no Command Line Access :-(

**Comment by rmnl** [comment]
@swissky You should just do this on your own computer. You do not need to do this on the server.

**Comment by swissky** [comment]
@rmnl thank you, it works. Now i working on the size.

Is there an Custom CSS way to make only one Player smaller? 

First Video inside the Post:

```
<script type='text/javascript' src='https://content.jwplatform.com/libraries/**jKRCnfBL.js**'></script>
			<div id='jwplayer_mhcmsvws_**jKRCnfBL**_div'></div>
		<script type='text/javascript'>
			if(typeof(jQuery)=="function"){(function($){$.fn.fitVids=function(){}})(jQuery)};
				jwplayer('jwplayer_mhcmsvws_**jKRCnfBL**_div').setup(
				{"playlist":"https:\/\/content.jwplatform.com\/feeds\/mhcmsvws.json","ph":2}
			);
		</script>
```


Second Video inside the Post:
```
<div id='jwplayer_oDHFY10T_**jKRCnfBL**_div'></div>
		<script type='text/javascript'>
			if(typeof(jQuery)=="function"){(function($){$.fn.fitVids=function(){}})(jQuery)};
				jwplayer('jwplayer_oDHFY10T_**jKRCnfBL**_div').setup(
				{"playlist":"https:\/\/content.jwplatform.com\/feeds\/oDHFY10T.json","ph":2}
			);
		</script>
```

If is ad this, all videos are smaller but i like the 16:9 size.

`.jwplayer {
width: 50% !important;
margin: 0 auto;
}`

**Comment by rmnl** [comment]
@swissky I'm not sure, you should contact [our support](https://support.jwplayer.com) for that.
