### ISSUE TITLE
Update location of API Keys on "Plugin Authorization" Page

### ISSUE THREAD

**Issue by waxidiotic** [jwplayer/wordpress-plugin#7]
The Plugin Authorization screen currently reads:

> Insert your JW Player API Credentials below. These are located in the Account > API Keys section of your dashboard.

However, the dashboard has since been updated to have the API keys listed in **Account > Properties > (Whatever Property)**.

**Comment by rmnl** [comment]
@waxidiotic Good catch. Will update this asap.
