### ISSUE TITLE
html5 player is coming up as flash

### ISSUE THREAD

**Issue by simsekahmett** [jwplayer/wordpress-plugin#74]
Hello all,

I'm using JW Player plugin for more than 4 years with premium account. 
I have an issue from certificate side of the browsers such as it always prompts users to allow Flash content for related page. The issue is that i've already changed rendering mode to html5 rather than flash but it still asks as flash content. I do not have anything other than player in the page (there is no other flash content).
You can reach a demo player page from following link: https://www.kruzem.com/viddem/

If you're not able to see the player please check the screenshot below;
![image](https://user-images.githubusercontent.com/20887939/45013125-a5b0bc80-b022-11e8-8612-31ad1ca9b391.png)

I want to get rid of this allowing steps and just want to make player visible at the first load. 
I'm using JW Player 6 Plugin for Wordpress with version: 2.1.14 
Also we are using JW player for RTMP streaming with secure token variables in our shortcode. The shortcode is like this;
[jwplayer player="0" rtmp.securetoken="XXX" file="rtmp://SERVER:PORT/vod/mp4:17yy2.mp4" provider="rtmp" ]

**Comment by rmnl** [comment]
@simsekahmett You are using our old plugin. This plugin no longer supports JW Player 6. It uses our cloud-hosted player, that you can manage in your dashboard. Please investigate the following articles for help with upgrading from JW6 to our latest version 8.

1. [JW6 to JW7 Migration Reference](https://support.jwplayer.com/articles/jw6-to-jw7-migration-reference)
2. [JW7 to JW8 Migration Reference](https://support.jwplayer.com/articles/jw7-to-jw8-migration-reference)
