### ISSUE TITLE
JW player destroyed my entire wordpress

### ISSUE THREAD

**Issue by farbrorolle** [jwplayer/wordpress-plugin#75]
Hello. I just installed JW player and now I can't access my wordpress page at all, not even my admin page. It just says 

Parse error: syntax error, unexpected '[' in /storage/content/75/103575/ollemarkensten.com/public_html/wp-content/plugins/jw-player-7-for-wp/admin/jwppp-admin.php on line 223

**Comment by rmnl** [comment]
Hello @farbrorolle. This is the repository for a [different Wordpress plugin](https://wordpress.org/plugins/jw-player/). By the look of the error you are using [this plugin](https://wordpress.org/plugins/jw-player-7-for-wp/).  Support for that plugin can be found [here](https://wordpress.org/support/plugin/jw-player-7-for-wp).
